FROM node:23-alpine3.20

WORKDIR /usr/src/app

# TODO: fix this
COPY ../../package.json ../../pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install

COPY ../../. .

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start:prod"]
